export const CHANGE_SONGS_CATEGORY = "songs/CHANGE_SONG_CATEGORY";
export const CHANGE_SONGS_CURRENT_CATEGORY = "songs/CHANGE_SONGS_CURRENT_CATEGORY";
export const CHNAGE_SONGS_CATEGORY_SONGS = "songs/CHNAGE_SONGS_CATEGORY_SONGS";
